### ISSUE TITLE
Add a way to tag generic data to a Property

### ISSUE THREAD

**Issue by jdfreder** [phosphorjs/phosphor-properties#2]
I need a generic way to tag custom data to [Properties](https://github.com/phosphorjs/phosphor-properties/blob/master/src/index.ts#L133).  I could use a Map to maintain my own association, but an any type `metadata` or `tag` key would be preferred.  My specific use case will be a string `name` associated with each property.

**Comment by sccolbert** [comment]
ping @blink1073 @dwillmer @jasongrout @sylvaincorlay for comments

**Comment by sccolbert** [comment]
I'm not opposed to this idea. One thought is whether `name` should just be a standard option instead of kept inside metadata. Can you think of other use cases for metadata, aside from names?

**Comment by blink1073** [comment]
I'd say leave it open, because we don't know what they might do with it, similar to `Atom.tag()`

**Comment by jdfreder** [comment]
I don't have any other use cases yet, I just figured, like @blink1073 mentioned, for the sake of venturing into the unknown!  I'm a-ok for only a string `name` key if you don't want the generic metadata key.

**Comment by SylvainCorlay** [comment]
I like the ideas of Properties being a js counterpart to Atom / Traitlets (without the meta magics), so +1 to use similar names for metadata.

**Comment by ellisonbg** [comment]
I think this is a good idea and agree with @SylvainCorlay on the naming of these things.

**Comment by sccolbert** [comment]
Fixed.
