### ISSUE TITLE
Add an `notify` property option

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor-properties#4]
As it says on the tin. If provided and `false`, this will disable emitting the changed signal for a property (the static change function will still be invoked). This will allow code to create "private" properties which cannot be observed by external code. It's also an optimization point for properties which don't need to be observed.

**Comment by dwillmer** [comment]
+1 for private properties.

**Comment by blink1073** [comment]
Sounds reasonable to me.
