### ISSUE TITLE
Add a `changed` signal to each Property *instance*

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor-properties#5]
Currently, the `Property` class has a static `changed` signal which is emitted when any property changes on any object. I'd like to augment this with an addition `changed` signal on a property *instance*. This would allow more fine-grained observing of specific properties.

**Comment by dwillmer** [comment]
+1

**Comment by blink1073** [comment]
Yep, sounds good.

**Comment by sccolbert** [comment]
@ellisonbg @jdfreder this is probably of significant interest to you
